### ISSUE TITLE
Output file flag is not parssed correctly

### ISSUE THREAD

**Issue by ZAZPRO** [KM8Oz/open_proxies#1]
On running executable while defining output file flag I do get error. Main branch. MacOS.

```bash
open_proxies -i ./socks.txt -o ./live.txt
error: The argument '--input <FILENAME>' cannot be used with '--out <FILENAME>'

Usage: open_proxies --input <FILENAME>

For more information try '--help'
```

**Comment by KM8Oz** [comment]
> open_proxies -i ./socks.txt -o ./live.txt

Thank you for rising this issue, I fixed it right away.
Fix: code version 0.1.1
